Song.create(name: 'Example', artist: 'Example', key_signature: 'G', time_signature: '4/4', abc_notation: '|:G2cc dedB|dedB dedB|c8|', info: 'Example', user_id: nil, date: 12022022)
Song.create(name: 'Example', artist: 'Example', key_signature: 'G', time_signature: '4/4', abc_notation: '|:G2c2c2c2|c2c2c2c2|c8|', info: 'Example', user_id: nil, date: 12042022)
Song.create(name: 'Example', artist: 'Example', key_signature: 'G', time_signature: '4/4', abc_notation: '|:G2c2c2c2|c2c2c2c2|c8|', info: 'Example', user_id: nil, date: 12052022)
Song.create(name: 'Example', artist: 'Example', key_signature: 'G', time_signature: '4/4', abc_notation: '|:G2c2c2c2|c2c2c2c2|c8|', info: 'Example', user_id: nil, date: 12062022)
Song.create(name: 'Example', artist: 'Example', key_signature: 'G', time_signature: '4/4', abc_notation: '|:G2c2c2c2|c2c2c2c2|c8|', info: 'Example', user_id: nil, date: 12072022)
Song.create(name: 'Example', artist: 'Example', key_signature: 'G', time_signature: '4/4', abc_notation: '|:G2c2c2c2|c2c2c2c2|c8|', info: 'Example', user_id: nil, date: 12082022)
Song.create(name: 'Example', artist: 'Example', key_signature: 'G', time_signature: '4/4', abc_notation: '|:G2c2c2c2|c2c2c2c2|c8|', info: 'Example', user_id: nil, date: 12092022)
Song.create(name: 'Example', artist: 'Example', key_signature: 'G', time_signature: '4/4', abc_notation: '|:G2c2c2c2|c2c2c2c2|c8|', info: 'Example', user_id: nil, date: 12102022)
Song.create(name: 'Example', artist: 'Example', key_signature: 'G', time_signature: '4/4', abc_notation: '|:G2c2c2c2|c2c2c2c2|c8|', info: 'Example', user_id: nil, date: 12112022)
Song.create(name: 'Example', artist: 'Example', key_signature: 'G', time_signature: '4/4', abc_notation: '|:G2c2c2c2|c2c2c2c2|c8|', info: 'Example', user_id: nil, date: 12122022)


Practice.create(name: 'Cmajor', first: 'C2DEFGAB', second: 'c2BAGFED', third: 'C2', first_note: 'c4', last_note: 'f5')
Practice.create(name: 'Gmajor', first: 'G2ABcde^f', second: 'g2^fedcBA', third: 'G2', first_note: 'g4', last_note: 'c6')
Practice.create(name: 'Dmajor', first: 'D2E^FGAB^c', second: 'd2^cBAG^FE', third: 'D2', first_note: 'd4', last_note: 'g5')
Practice.create(name: 'Amajor', first: 'A2B^cde^f^g', second: 'a2^g^fed^cB', third: 'A2', first_note: 'a4', last_note: 'd6')
Practice.create(name: 'Emajor', first: 'E2^F^GAB^c^d', second: 'e2^d^cBA^G^F', third: 'E2', first_note: 'e4', last_note: 'a5')
Practice.create(name: 'Bmajor', first: 'B2^c^de^f^g^a', second: 'b2^a^g^fe^d^c', third: 'B2', first_note: 'b4', last_note: 'e6')
